apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace}}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.count }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        imagePullPolicy: IfNotPresent
        image: {{ .Values.app.image }}:{{ .Values.app.tag }}
        resources:
          limits:
            memory: "{{ .Values.app.memory }}"
            cpu: "{{ .Values.app.cpu }}"
        ports:
        - containerPort: {{ .Values.app.targetPort }}