apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-tcp
  namespace: {{ .Values.app.namespace}}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.app.NodePort }}