app:
  name: "viwell-countries"
  port: 8080
  count: 1
  image: "622931036635.dkr.ecr.eu-west-3.amazonaws.com/viwell-countries"
  tag: "1.0.1-v1"
  serviceName: viwell-countries
  memory: 512Mi
  cpu: 250m
  namespace: viwell
  targetPort: 8080
  NodePort: 30380
  host: countries.apps.org