apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-tcp
  namespace: {{ .Values.app.namespace}}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.targetPort }}
      nodePort: {{ .Values.app.NodePort }}