name: build viwell apps
run-name: ${{ github.actor }} started pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - run: echo ${{ github.workspace }}
      - run: docker --version
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - run: helm version
      - run: echo "🍏 This job's status is ${{ job.status }}."