name: Build Viwell applications

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-3
  ECR_REPO_Countries: viwell-countries
  ECR_REPO_Airports: viwell-airports

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push image for Countries app to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPO_Countries:$IMAGE_TAG ./viwell-countries
          docker tag $ECR_REGISTRY/$ECR_REPO_Countries:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPO_Countries:1.0.1-v1
          docker push $ECR_REGISTRY/$ECR_REPO_Countries:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPO_Countries:1.0.1-v1
          echo "image=$ECR_REGISTRY/$ECR_REPO_Countries:$IMAGE_TAG" >> $GITHUB_OUTPUT
          
      - name: Build and push helm for Countries App to Amazon ECR
        run: |
          helm package ./viwell-countries/devops-tools/helm
          helm chart push $ECR_REGISTRY/$ECR_REPO_Countries:viwell-countries-1.0.1.tgz